settings:
  head-protection: true
  hide-default-join-quit: true

priority-access:
  enabled: true
  normal-limit: 180
  max-limit: 190
messages:
  kick-full: "&#FFA500Сервер переполнен! Для входа требуется привилегия &FFFF00ɢᴀꜱᴛ."
  priority: "&#FFA500Сервер почти полон! Только игроки с правом &f{permission} &#FFA500могут зайти."